### PR TITLE
add threshold min/max/inc to Fiji codes

### PR DESCRIPTION
**Pull request by poilvert**
I also added a new simple test to compute a single rand value and it is fast !

### CODE REVIEW

**Comment by npinto** [comment]
Looks good right? Let's merge (it doesn't have to be super clean since it's in the isbi12 sandbox). we may have to move to `wildwest.isbi12` just to make sure ;-)

**Comment by poilvert** [comment]
sure. The codes are working for sure. I use them all the time ;-)

**Comment by poilvert** [comment]
should we merge ?

**Comment by npinto** [comment]
Would you mind making the move to `wildwest.isbi12` ?

**Comment by poilvert** [comment]
is it better this way ?

**Comment by npinto** [comment]
Thanks!

**Pull request merged**
